---
# tasks file for kibana-role
- name: Copy kibana File in tmp
  copy:
    src: files/kibana-{{ kibana_version }}-linux-x86_64.tar.gz
    dest: /tmp
    mode: 0644
- name: Create directrory for kibana
  file:
    state: directory
    path: "{{ kibana_home }}"
    mode: 0644
  tags: kibana
- name: Extract Kibana in the installation directory
  unarchive:
    copy: false
    src: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
    dest: "{{ kibana_home }}"
    extra_opts: [--strip-components=1]
    creates: "{{ kibana_home }}/bin/kibana"
  tags:
    - skip_ansible_lint
    - kibana
- name: Set environment Kibana
  template:
    src: templates/kib.sh.j2
    dest: /etc/profile.d/kib.sh
    mode: 0644
  tags: kibana